### ISSUE TITLE
Playtimes are gone after restart

### ISSUE THREAD

**Issue by Milkman337** [NGnius/NonSteamPlaytime#1]
As the title says the playtimes are not getting saved into the json file after for example restarting. I tried a little bit to fix it and it seems like the issue is in the save function. It seems to have an error or something as when I log before the save and after the save only the log before the save is in the log file also any logs in the save file are also not getting called.

**Comment by Milkman337** [comment]
alright so I looked a little more into it and it seems like the json.dumb doesnt specify in to dump it into save_data.

**Comment by Milkman337** [comment]
but that didnt fix it ok now I dont know what to do anymore

**Comment by NGnius** [comment]
Thanks for the PR, I managed to do it myself since you closed it. Of course it's still not reliable because the playtime is reset in the UI in some cases. But that's not something I'm going to fix on my own.
